from __future__ import annotations

from codeatlas.embedding.base import EmbeddingProvider as EmbeddingGenerator
from codeatlas.embedding.fastembed_provider import FastEmbedProvider as LocalEmbeddingGenerator
from codeatlas.embedding.hash_provider import HashEmbeddingProvider as HashEmbeddingGenerator
